version: 1.0.{build}

image: Visual Studio 2017

environment:
  matrix:
    - solution_name: SimpleFTPServer/SimpleFTPServer.sln

before_build:
  - cmd: nuget restore SimpleFTPServer/SimpleFTPServer.sln

build_script:
  - msbuild SimpleFTPServer/SimpleFTPServer.sln