version: 1.0.{build}

image: Visual Studio 2017
      
  - solution_name: MyNUnit/MyNUnit.sln    
    
  before_build:
    - cmd: MyNUnit/MyNUnit.sln    

  build_script:
    - msbuild MyNUnit/MyNUnit.sln