version: 1.0.{build}
image: Visual Studio 2017
    
for:
-
  branches:
    only:
      - sem4_ex3

  before_build:
    - nuget restore "sem 4/Exercise 3/Exercise 3.sln"

  build:
    project: "sem 4/Exercise 3/Exercise 3.sln"

  test_script:
    - dotnet test "sem 4/Exercise 3/Exercise 3.sln"
    
-
  branches:
    only:
      - sem4_ex4
      
- 
  branches:
    only:
      - sem4_ex5

  before_build:
    - nuget restore "sem 4/Exercise 5/Exercise 5.sln"

  build:
    project: "sem 4/Exercise 5/Exercise 5.sln"

  test_script:
    - dotnet test "sem 4/Exercise 5/Exercise 5.sln"