version: 1.0.{build}

image: Visual Studio 2017

environment:
  matrix:
    - solution_name: Lazy/Lazy.sln
    - solution_name: MyThreadPool/MyThreadPool.sln

before_build:
  - cmd: nuget restore Lazy/Lazy.sln
  - cmd: nuget restore MyThreadPool/MythreadPool.sln

build_script:
  - msbuild Lazy/Lazy.sln
  - msbuild MyThreadPool/MyThreadPool.sln