version: 1.0.{build}

image: Visual Studio 2017
      
branches: 
  only:
    - mythreadpool
before_build:
  - nuget restore MyThreadPool/MythreadPool.sln
build:
  project: MyThreadPool/MyThreadPool.sln
