image: Visual Studio 2017
    
for:
-
  branches:
    only:
      - sem4_ex3

  before_build:
    - nuget restore "sem 4/Exercise 3/Exercise 3.sln"

  build:
    project: "sem 4/Exercise 3/Exercise 3.sln"

  test_script:
    - dotnet test "sem 4/Exercise 3/Exercise 3.sln"
    
-
  branches:
    only:
      - sem4_ex4
      
  before_build:
    - nuget restore "sem 4/Exercise 4/Lambda Interpreter/Lambda Interpreter.sln"
    
  build:
    project: "sem 4/Exercise 4/Lambda Interpreter/Lambda Interpreter.sln"
    
  test_script:
    - dotnet test "sem 4/Exercise 4/Lambda Interpreter/Lambda Interpreter.sln"
- 
  branches:
    only:
      - sem4_ex5

  before_build:
    - nuget restore "sem 4/Exercise 5/Exercise 5.sln"

  build:
    project: "sem 4/Exercise 5/Exercise 5.sln"

  test_script:
    - dotnet test "sem 4/Exercise 5/Exercise 5.sln"
    
- 
  branches:
    only:
      - sem4_ex7   
      
  before_build:
    - nuget restore "sem 4/Exercise 7/Exercise 7.sln"

  build:
    project: "sem 4/Exercise 7/Exercise 7.sln"

  test_script:
    - dotnet test "sem 4/Exercise 7/Exercise 7.sln"
- 
  branches:
    only:
      - sem4_ex6

  before_build:
    - nuget restore "sem 4/Exercise 6/Exercise 6.sln"

  build:
    project: "sem 4/Exercise 6/Exercise 6.sln"

  test_script:
    - dotnet test "sem 4/Exercise 6/Exercise 6.sln"

- 
  branches:
    only:
      - sem4_ex8

  before_build:
    - nuget restore "sem 4/Exercise 8/Exercise 8.sln"

  build:
    project: "sem 4/Exercise 8/Exercise 8.sln"

  test_script:
    - dotnet test "sem 4/Exercise 8/Exercise 8.sln"

- 
  branches:
    only:
      - lambda_calculus

  before_build:
    - nuget restore "sem 4/Exercise 4/Lambda Interpreter/Lambda Interpreter.sln"

  build:
    project: "sem 4/Exercise 4/Lambda Interpreter/Lambda Interpreter.sln"

  test_script:
    - dotnet test "sem 4/Exercise 4/Lambda Interpreter/Lambda Interpreter.sln"